### ISSUE TITLE
`quartz enclave start` appears that `--unsafe-trust-latest` does not work 

### ISSUE THREAD

**Issue by davekaj** [informalsystems/cycles-quartz#237]
When I tried to run
```bash
quartz  enclave start  --fmspc "00606A000000" --tcbinfo-contract "neutron1anj45ushmjntew7zrg5jw2rv0rwfce3nl5d655mzzg8st0qk4wjsds4wps" --dcap-verifier-contract "neutron18f3xu4yazfqr48wla9dwr7arn8wfm57qfw8ll6y02qsgmftpft6qfec3uf" --unsafe-trust-latest
```
I got the error 
```
Peforming Enclave Start
Error:
   0: unspecified error: No such file or directory (os error 2)
```
It was not able to read from the files `trusted.hash` and `trusted.height`. `--unsafe-trust-latest` should have created these files. 

I was able to fix it by going to the neutron testnet and manually getting the block and hash and adding it to `quartz.toml`.

So I created this issue to track this. If we can't reproduce it over the next while, we can remove it. But I wanted to document it in case anyone else comes across it.

**Comment by ebuchman** [comment]
Hasn't been reproduced
