### ISSUE TITLE
Should we store TcbInfos for all known fmspcs on the contract? 

### ISSUE THREAD

**Issue by hu55a1n1** [informalsystems/cycles-quartz#243]
## Summary
This was @dusterbloom's suggestion to simplify the dev journey. Found a list here ->https://github.com/Ruteri/tcbinfo-monitor/blob/main/tcbs.json

## Acceptance Criteria
TBD

**Comment by dusterbloom** [comment]
All FMSPCs on neutron pion-1 testnet chain - [here](https://neutron.celat.one/pion-1/contracts/neutron1anj45ushmjntew7zrg5jw2rv0rwfce3nl5d655mzzg8st0qk4wjsds4wps)
